version: '3.8'

services:
  frontend:
    build: computer_vision_concrete/frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - computer_vision_concrete/frontend:/app_frontend
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: ./computer_vision_concrete/backend
    ports:
      - 8000:8000
    volumes:
      - computer_vision_concrete/backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
